travis:
  secure:
    BINSTAR_TOKEN: Acj89YRFkmXtRZSZQOYRg8FhW3ZTYjBfaFmDJ4sWdw6Upi8mdogRQrnLQwuJ80E2t1ODjqLVejKRbyjc+H1a8vt3XR8BSO2RKplf5Q2nzdleZho0fE4Kaa30fb4a3SFE/JipF7LvPd6WJpUyd3Vr0vUFurRYKWnHub3p8jD/h/IbPB7/7f5LONF0jdMXeTQ4r2T6OX2/ieSCkSQhgfaiM0xlukCHI8ehxt/IeonJHWuDl24YQcy+0frgrlwg2ByZotCI0s1UncwCOLlJ4f8UkfUodfD62xflpe7D+qo5lubDc4TnU8o5xzamPWwBKZBCFNhCGJsuXyZsx5BRuWkwnHrsI9kvl7k/PUowm7towayFV1T5rdDmu0nofmVY/HwUH4XKUMnuiiYHrCya8ymchGYEJcufT4AcJuAIi9ewuehfgKpl0esGcVT+uLsuDgnIXuB4glpjuzQTbzKeXrVTyr18EtE+ZhyfqQuJTK+7jbP+r55nZx+rrVZ2UzBKoGc1gCSW7vRoEUqn+YHnb3KSuJnR7JLc7RACWluLS7lwdeaohMTqn11vLqFqX/hWEgxZW1b1LuSeWlez7x+lKmZ177RZvg0IvP3/SUO4EfgVU+HFOpMUMklfh2duNDaEZkW0vhtoTFWQ7DtEFFMYadCPkOHF4sswqXxaxctAk5nr6Zk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
